CONFIG_LOG=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_INIT_STACKS=y

CONFIG_POWEROFF=y

CONFIG_SENSOR=y

CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y

CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_ARP=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_SOCKETS=y

CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y

CONFIG_DNS_RESOLVER=y

# Added to prevent error with missing #include <ethernet/eth_stats.h> for esp_wifi_drv.c
CONFIG_NET_L2_ETHERNET=y
